"use client";

import { useState, useMemo } from "react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
} from "recharts";
import jsPDF from "jspdf";

export default function RetirementCalculator() {
  /* ---------------- STATE ---------------- */
  const [currentAge, setCurrentAge] = useState(25);
  const [retirementAge, setRetirementAge] = useState(60);
  const [savings, setSavings] = useState(5000);
  const [monthly, setMonthly] = useState(200);
  const [rate, setRate] = useState(7);

  /* EMAIL POPUP STATE */
  const [showPopup, setShowPopup] = useState(false);
  const [email, setEmail] = useState("");
  const [error, setError] = useState("");

  /* ---------------- CALCULATION ---------------- */
  const result = useMemo(() => {
    let balance = savings;
    let chart = [];

    for (let age = currentAge; age <= retirementAge; age++) {
      balance += monthly * 12;
      balance *= 1 + rate / 100;
      chart.push({ age, value: Math.round(balance) });
    }

    const invested = savings + monthly * 12 * (retirementAge - currentAge);

    return {
      final: balance,
      invested,
      profit: balance - invested,
      chart,
    };
  }, [currentAge, retirementAge, savings, monthly, rate]);

  /* ---------------- PDF FUNCTION ---------------- */
  const downloadPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("Retirement Report", 20, 20);

    doc.setFontSize(12);
    doc.text(`Current Age: ${currentAge}`, 20, 40);
    doc.text(`Retirement Age: ${retirementAge}`, 20, 50);
    doc.text(`Monthly Investment: $${monthly}`, 20, 60);
    doc.text(`Return Rate: ${rate}%`, 20, 70);

    doc.setFontSize(14);
    doc.text("Results", 20, 90);

    doc.setFontSize(12);
    doc.text(`Final Wealth: $${result.final.toFixed(2)}`, 20, 105);
    doc.text(`Total Invested: $${result.invested.toFixed(2)}`, 20, 115);
    doc.text(`Profit: $${result.profit.toFixed(2)}`, 20, 125);

    doc.setFontSize(10);
    doc.text("Generated by ToolioFinance", 20, 150);

    doc.save("retirement-report.pdf");
  };

  /* ---------------- EMAIL SUBMIT ---------------- */
  const handleEmailSubmit = () => {
    if (!email.includes("@")) {
      setError("Please enter a valid email");
      return;
    }

    localStorage.setItem("user_email", email);

    setShowPopup(false);
    setEmail("");
    setError("");

    downloadPDF(); // 🔥 unlock PDF
  };

  return (
    <div className="min-h-screen bg-linear-to-br from-slate-100 to-white px-4 py-8">
      {/* HEADER */}
      <div className="max-w-6xl mx-auto mb-6">
        <h1 className="text-3xl font-bold text-slate-800">
          Retirement Calculator
        </h1>
        <p className="text-slate-500">
          Plan your future wealth with smart projections
        </p>
      </div>

      <div className="max-w-6xl mx-auto grid lg:grid-cols-3 gap-6">
        {/* INPUTS */}
        <div className="bg-cyan-50 p-6 rounded-2xl shadow space-y-4">
          <h2 className="font-semibold text-lg">Your Inputs</h2>

          <Input label="Current Age" value={currentAge} set={setCurrentAge} />
          <Input
            label="Retirement Age"
            value={retirementAge}
            set={setRetirementAge}
          />
          <Input label="Current Savings ($)" value={savings} set={setSavings} />
          <Input
            label="Monthly Investment ($)"
            value={monthly}
            set={setMonthly}
          />
          <Input label="Expected Return (%)" value={rate} set={setRate} />

          <button
            onClick={() => setShowPopup(true)}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white py-2 rounded-lg mt-3"
          >
            Download PDF Report
          </button>
        </div>

        {/* CHART */}
        <div className="lg:col-span-2 bg-blue-100 p-6 rounded-2xl shadow">
          <h3 className="font-semibold mb-4">Growth Projection</h3>

          <div className="w-full h-65 sm:h-80 md:h-96">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={result.chart}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="age" />
                <YAxis />
                <Tooltip />
                <Line
                  type="monotone"
                  dataKey="value"
                  stroke="#2563eb"
                  strokeWidth={3}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* RESULT CARDS */}
      <div className="max-w-6xl mx-auto grid sm:grid-cols-3 gap-4 mt-6">
        <Card title="Final Wealth" value={result.final} />
        <Card title="Total Invested" value={result.invested} />
        <Card title="Profit" value={result.profit} highlight />
      </div>

      {/* CTA */}
      <div className="max-w-6xl mx-auto mt-8 bg-blue-600 text-white p-6 rounded-2xl flex flex-col md:flex-row justify-between items-center">
        <div>
          <h3 className="text-lg font-bold">
            Start investing smarter today 🚀
          </h3>
          <p className="text-sm opacity-80">
            Use this plan with top investment platforms
          </p>
        </div>

        <button className="mt-3 md:mt-0 bg-white text-blue-600 px-5 py-2 rounded-lg font-semibold">
          Get Investment Plan
        </button>
      </div>

      {/* EMAIL POPUP */}
      {showPopup && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 px-4">
          <div className="bg-white p-6 rounded-2xl shadow-xl w-full max-w-md">
            <h2 className="text-xl font-bold mb-2">Get Your Free Report</h2>

            <p className="text-sm text-gray-500 mb-4">
              Enter your email to download your retirement PDF
            </p>

            <input
              type="email"
              placeholder="Enter your email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full p-2 border rounded-lg mb-2"
            />

            {error && <p className="text-red-500 text-sm mb-2">{error}</p>}

            <button
              onClick={handleEmailSubmit}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white py-2 rounded-lg"
            >
              Download Now
            </button>

            <button
              onClick={() => setShowPopup(false)}
              className="w-full mt-2 text-sm text-gray-500"
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

/* INPUT COMPONENT */
function Input({ label, value, set }) {
  return (
    <div>
      <label className="text-sm font-medium text-slate-700">{label}</label>
      <input
        type="number"
        value={value}
        onChange={(e) => set(+e.target.value)}
        className="w-full mt-1 p-2 rounded-lg border focus:ring-2 focus:ring-blue-500 outline-none"
      />
    </div>
  );
}

/* CARD */
function Card({ title, value, highlight }) {
  return (
    <div
      className={`p-5 rounded-xl shadow ${highlight ? "bg-green-100" : "bg-white"}`}
    >
      <p className="text-sm text-gray-500">{title}</p>
      <p className="text-xl font-bold text-gray-800 mt-1">
        ${value.toFixed(0)}
      </p>
    </div>
  );
}
